import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient();
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId="287221084975-s2uu87brisf5aul8duondpsso1bc3lr8.apps.googleusercontent.com">
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
